/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-03-29 07:24:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/../common/head.jsp", Long.valueOf(1427526555746L));
    _jspx_dependants.put("/../common/public.jsp", Long.valueOf(1427360243243L));
    _jspx_dependants.put("/../common/main.jsp", Long.valueOf(1427526244397L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html >\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta HTTP-EQUIV=\"Cache-Control\" CONTENT=\"no-cache, must-revalidate\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
 pageContext.setAttribute("root", request.getContextPath()); 
      out.write("\r\n");
      out.write("<title>拓客管理系统</title>\r\n");
      out.write("<meta HTTP-EQUIV=\"pragma\" CONTENT=\"no-cache\">\r\n");
      out.write("<meta HTTP-EQUIV=\"Cache-Control\" CONTENT=\"no-cache, must-revalidate\">\r\n");
      out.write("<meta HTTP-EQUIV=\"expires\" CONTENT=\"0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<input type=\"hidden\" id=\"root\" value=\"/SanTuo\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/ui.jqgrid.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/ace.min.css\" />\r\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/font-awesome.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/jquery-ui-1.10.3.full.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/datepicker.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/ace.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/ace-rtl.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/ace-skins.min.css\" />\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/jquery-2.0.3.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/date-time/bootstrap-datepicker.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/ace.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/ace-extra.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/jqGrid/jquery.jqGrid.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/jqGrid/i18n/grid.locale-en.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/fuelux/data/fuelux.tree-sampledata.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/ace-elements.min.js\"></script>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/bootstrap-treeview.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/common.js\"></script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/ztree/css/zTreeStyle/zTreeStyle.css\" />\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/ztree/jquery.ztree.all-3.5.js\"></script>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".list-group {\r\n");
      out.write("\tpadding-left: 0;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta HTTP-EQUIV=\"Cache-Control\" CONTENT=\"no-cache, must-revalidate\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"addGroupModal\" tabindex=\"-1\" style=\"z-index: 99999\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("   <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("         <div class=\"modal-header\">\r\n");
      out.write("            <button type=\"button\" class=\"close\"  data-dismiss=\"modal\" aria-hidden=\"true\">\r\n");
      out.write("                  &times;\r\n");
      out.write("            </button>\r\n");
      out.write("            <h4 class=\"modal-title\" id=\"myModalLabel\">\r\n");
      out.write("               \t\t添加组\r\n");
      out.write("            </h4>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"modal-body\">\r\n");
      out.write("         <div class=\"form-horizontal\">\r\n");
      out.write("         <form id=\"addGroupForm\">\r\n");
      out.write("         \t\t<input type=\"hidden\" name=\"pid\" id=\"pid\">\r\n");
      out.write("  \t\t\t\t<div class=\"form-group\">\r\n");
      out.write("   \t\t\t\t\t\t<label  class=\"col-sm-2 control-label\" style=\"cursor: pointer;\">组名</label>\r\n");
      out.write("    \t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("    \t\t\t\t\t\t<input class=\"form-control\" id=\"groupName\" name=\"name\" type=\"text\" >\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t</div>  \r\n");
      out.write("  \t\t\t</form>\r\n");
      out.write("           \t   <br>\r\n");
      out.write("\t         \r\n");
      out.write("\t        </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"modal-footer\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-default\" \r\n");
      out.write("               data-dismiss=\"modal\">关闭\r\n");
      out.write("            </button>\r\n");
      out.write("            <button type=\"button\" onclick=\"saveGroup()\" class=\"btn btn-primary\">\r\n");
      out.write("            \t\t保存\r\n");
      out.write("            </button>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div><!-- /.modal-content -->\r\n");
      out.write("</div><!-- /.modal -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \t\t<div class=\"navbar navbar-default\" id=\"navbar\">\r\n");
      out.write("\t\t\t<div class=\"navbar-container\" id=\"navbar-container\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header pull-left\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"navbar-brand\">\r\n");
      out.write("\t\t\t\t\t\t<small>\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"icon-leaf\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t善拓后台管理系统\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</a><!-- /.brand -->\r\n");
      out.write("\t\t\t\t</div><!-- /.navbar-header -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header pull-right\" role=\"navigation\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<a href=\"#\" onclick=\"goifm('report_review.jsp')\" class=\"navbar-brand\">\r\n");
      out.write("\t\t\t\t\t<small> 审阅:<span id=\"shenyue\" >0</span></small>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" onclick=\"goifm('waring_history.jsp')\" class=\"navbar-brand\">\r\n");
      out.write("\t\t\t\t\t<small> 报警:<span id=\"warning\" >0</span></small>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"navbar-brand\">\r\n");
      out.write("\t\t\t\t\t<small><button onclick=\"logout()\" class=\"btn btn-info\">退出</button> </small>\r\n");
      out.write("\t\t\t\t</a>\t\r\n");
      out.write("\t\t\t\t</div><!-- /.navbar-header -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"main-container\" id=\"main-container\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"main-container-inner\">\r\n");
      out.write("\t\t\t\t<a class=\"menu-toggler\" id=\"menu-toggler\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t<span class=\"menu-text\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"sidebar\" id=\"sidebar\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul id=\"ulList\" class=\"nav nav-list\">\r\n");
      out.write("\t\t\t\t\t\t<li id=\"qx1\" class=\"open\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"  class=\"dropdown-toggle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-cog\"></i><span class=\"menu-text\">账号管理 </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b class=\"arrow icon-angle-down\"></b>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul  class=\"submenu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li id=\"qx2\" ><a href=\"#\" onclick=\"goifm('account_company.jsp')\"><i class=\"icon-double-angle-right\"></i>公司管理</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li id=\"qx3\"><a href=\"#\" onclick=\"goifm('account_project.jsp')\"><i class=\"icon-double-angle-right\"></i>项目管理</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li id=\"qx4\"><a href=\"#\" onclick=\"goifm('ar')\"><i class=\"icon-double-angle-right\"></i>角色管理</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li id=\"qx5\"><a href=\"#\" onclick=\"goifm('au')\"><i class=\"icon-double-angle-right\"></i>用户管理</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"qx6\"> \r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"  class=\"dropdown-toggle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon-group\" ></i><span class=\"menu-text\">外场人员管理</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b class=\"arrow icon-angle-down\"></b>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"tree\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"qx7\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-edit\"></i><span class=\"menu-text\">任务管理 </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b class=\"arrow icon-angle-down\"></b>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"submenu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li id=\"qx8\"><a href=\"#\" onclick=\"goifm('task_rewoard.jsp')\" ><i class=\"icon-double-angle-right\"></i>奖励措施</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li id=\"qx9\"><a href=\"#\" onclick=\"goifm('task.jsp')\"><i class=\"icon-double-angle-right\"></i>任务设定</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li id=\"qx10\"><a href=\"#\" onclick=\"goifm('task_over.jsp')\"><i class=\"icon-double-angle-right\"></i>任务统计</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li  id=\"qx11\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" onclick=\"goifm('leave_electric.jsp')\"  class=\"dropdown-toggle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-phone-alt\"></i><span class=\"menu-text\">留电管理 </span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li  id=\"qx14\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" onclick=\"goifm('car_apply.jsp')\"  class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon-dashboard\"></i><span class=\"menu-text\">用车申请 </span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li  id=\"qx16\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" onclick=\"goifm('report_review.jsp')\" class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-check\"></i><span class=\"menu-text\">审阅</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"qx15\" class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" onclick=\"goifm('report')\" class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon-hdd\"></i><span class=\"menu-text\">上报 </span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li  id=\"qx17\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-record\"></i><span class=\"menu-text\">预警 </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b class=\"arrow icon-angle-down\"></b>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"submenu\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" onclick=\"goifm('warning.jsp')\" ><i class=\"icon-double-angle-right\"></i>划定预警圈</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" onclick=\"goifm('waring_history.jsp')\"><i class=\"icon-double-angle-right\"></i>报警历史记录</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"sidebar-collapse\" id=\"\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-double-angle-left\"></i>  \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t         var b=true;\r\n");
      out.write("\t\t\t\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\tloadTree();\r\n");
      out.write("\t\t\t\t\t\t\t\tsetInterval(sansuo, 500);\r\n");
      out.write("\t\t\t\t\t\t\t\tqueryStatus();\r\n");
      out.write("\t\t\t\t\t\t\t\tsetAuthority();\r\n");
      out.write("\t\t\t\t\t\t\t//\tsetInterval(queryStatus, 5000);\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t//权限\r\n");
      out.write("\t\t\t\t\t\t\tfunction setAuthority(){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"li[id^=qx]\").hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\turl :getval('root')+\"/user/queryAuthority\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcontentType : 'application/x-www-form-urlencoded;charset=utf-8',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$.each(data,function(i,o) {   \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$(\"#qx\"+o.FID).show();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t//状态\r\n");
      out.write("\t\t\t\t\t\t\tfunction queryStatus(){\r\n");
      out.write("\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\turl :getval(\"root\")+\"/status/query\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata :{},\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontentType : 'application/x-www-form-urlencoded;charset=utf-8',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif(data.r>0){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#shenyue\").html(data.r);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#shenyue\").addClass(\"sansuo\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(\"#shenyue\").removeClass(\"sansuo\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif(data.w>0){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(\"#warning\").html(data.w);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(\"#warning\").addClass(\"sansuo\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$(\"#warning\").removeClass(\"sansuo\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tfunction sansuo() {\r\n");
      out.write("\t\t\t\t\t\t\t\tif (b) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tb = false;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\".sansuo\").css(\"color\", \"blue\");\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tb = true;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\".sansuo\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tfunction logout(){\r\n");
      out.write("\t\t\t\t\t\t\t\twindow.location.href=getval(\"root\")+'/logout';\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t//加载树结构\r\n");
      out.write("\t\t\t\t\t\t\tfunction loadTree(){\r\n");
      out.write("\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\turl :getval(\"root\")+\"/outuser/queryTree\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata :{cid:10},\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontentType : 'application/x-www-form-urlencoded;charset=utf-8',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$('#tree').treeview({data: data}); \r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tfunction getGtoupHTml(id,name){\r\n");
      out.write("\t\t\t\t\t\t\t\treturn \t'<li style=\"\" data-nodeid=\"2\" class=\"list-group-item node-tree\"><span class=\"indent\"></span><span class=\"indent\"></span><span class=\"expand-collapse glyphicon\"></span><span class=\"icon glyphicon glyphicon-menu-hamburger\"></span><span id=\"group'+id+'\" onclick=\"goifm(\\'OutUser.jsp?gid='+id+'\\')\">'+name+'&nbsp;&nbsp;<span title=\"删除组\" onclick=\"delGroup(\\''+id+'\\')\" class=\"glyphicon glyphicon-minus-sign\"></span></span></li>';\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tfunction delGroup(id){\r\n");
      out.write("\t\t\t\t\t\t\t\tif(confirm(\"删除后组下账号一并删除\")){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t $.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\turl :getval(\"root\")+\"/au/delGroup\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata :{gid:id},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcontentType : 'application/x-www-form-urlencoded;charset=utf-8',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tloadTree();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}); \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tfunction saveGroup(){\r\n");
      out.write("\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\turl :getval(\"root\")+\"/au/addGroup\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata :$(\"#addGroupForm\").serialize(),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcontentType : 'application/x-www-form-urlencoded;charset=utf-8',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tloadTree();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$(\"#addGroupModal\").modal('toggle');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tfunction addGroup(id){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#pid\").val(id);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#addGroupModal\").modal('show');\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t</script>");
      out.write("\r\n");
      out.write("\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<meta HTTP-EQUIV=\"Cache-Control\" CONTENT=\"no-cache, must-revalidate\">\r\n");
      out.write("    \t\t<div class=\"breadcrumbs\" id=\"breadcrumbs\">\r\n");
      out.write("\t\t\t\t<div style=\"float: left;margin-left: 20px;\">实时动态：</div>\r\n");
      out.write("\t\t\t\t<div style=\"float: left;height: 20px\"> \r\n");
      out.write("\t\t\t\t\t<marquee direction=\"left\" scrollamount=\"3\" onmouseover=\"this.stop\"\r\n");
      out.write("\t\t\t\t\t\tonmouseout=\"this.start\" style=\"position:relative;\">\r\n");
      out.write("\t\t\t\t\t \t<span \r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: black;font-size: 18px;position:relative;cursor: pointer;\">当前小蜜蜂任务完成数量总数:<font\r\n");
      out.write("\t\t\t\t\t\t\tcolor=\"red\"><span id=\"SumOrder\">0</span>\r\n");
      out.write("\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</marquee>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"float: right; font-size: 18px\">登录用户 ：<i style=\"color: blue;\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.columns[\"UNAME\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</i></div>\r\n");
      out.write("\t\t\t</div>");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"iframediv\" style=\"width: 100%;\" >\r\n");
      out.write("\t\t\t\t<iframe id=\"iframe\" width=\"100%\" height=\"100%;\" name=\"iframe\" style=\"\" \tscrolling=\"auto\" frameborder=\"0\" src=\"\"> </iframe> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var heigth = $(window).height();\r\n");
      out.write("var width = $(window).width();\r\n");
      out.write("$(\"#iframediv\").height(heigth -100);\r\n");
      out.write("//ui-jqgrid-title\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /index.jsp(18,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user==null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t<script type=\"text/javascript\">\r\n");
        out.write("\t\t\t\tgoUrl('login.jsp');\r\n");
        out.write("\t\t\t</script>\r\n");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
